services:
  - type: web
    name: betatag
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /status
    envVars:
      - key: MAX_PLAYERS_PER_ROOM
        value: "10"
      - key: TRANSFORM_RATE_LIMIT
        value: "45"
